// @generated by scripts/generate-protocol.mjs — DO NOT EDIT.
// Source: Rinari Engine Protocol v1 (sha256:a98da08bca906d91075f1a2e77971a8a45b8d1bbb7affbcf6a9c0274aa1e39f9)

use serde::{Deserialize, Serialize};

macro_rules! define_methods {
    ($( $variant:ident => $name:literal ),* $(,)?) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum Method { $( $variant ),* }
        impl Method {
            pub fn as_str(self) -> &'static str {
                match self { $( Method::$variant => $name ),* }
            }
            pub const ALL: &'static [Method] = &[ $( Method::$variant ),* ];
        }
    };
}

define_methods! {
    EngineInfo => "engine.info",
    RuntimeSnapshotGet => "runtime.snapshot.get",
    SessionMove => "session.move",
    WorkspaceFileRead => "workspace.file.read",
    WorkspacePreviewStart => "workspace.preview.start",
    WorkspacePreviewStatus => "workspace.preview.status",
    WorkspacePreviewStop => "workspace.preview.stop",
    QuestionList => "question.list",
    QuestionResolve => "question.resolve",
    SessionList => "session.list",
    SessionGet => "session.get",
    SessionCreate => "session.create",
    SessionOpen => "session.open",
    SessionRename => "session.rename",
    SessionArchive => "session.archive",
    SessionRestore => "session.restore",
    SessionDelete => "session.delete",
    SessionFork => "session.fork",
    SessionHistory => "session.history",
    SessionModeSet => "session.mode.set",
    SessionModelSet => "session.model.set",
    SessionPermissionGet => "session.permission.get",
    SessionPermissionSet => "session.permission.set",
    SessionTurnStart => "session.turn.start",
    TargetList => "target.list",
    TargetAdd => "target.add",
    OperationStart => "operation.start",
    OperationGet => "operation.get",
    OperationCancel => "operation.cancel",
    SessionTurnCancel => "session.turn.cancel",
    SessionEvents => "session.events",
    SessionTimeline => "session.timeline",
    ApprovalResolve => "approval.resolve",
    TurnChangesGet => "turn.changes.get",
    TurnChangesReview => "turn.changes.review",
    TurnChangesUndoPreview => "turn.changes.undo.preview",
    TurnChangesUndo => "turn.changes.undo",
    ProjectList => "project.list",
    ProjectGet => "project.get",
    ProjectAdd => "project.add",
    ProjectUpdate => "project.update",
    ProjectRemove => "project.remove",
    ProjectListRecent => "project.list_recent",
    ProjectOpen => "project.open",
    ProjectStatus => "project.status",
    ProjectIntelligence => "project.intelligence",
    ProjectTrust => "project.trust",
    ProjectChanges => "project.changes",
    ProjectDiff => "project.diff",
    ProviderList => "provider.list",
    ProviderGet => "provider.get",
    ProviderCreate => "provider.create",
    ProviderUpdate => "provider.update",
    ProviderRemove => "provider.remove",
    ProviderTest => "provider.test",
    ProviderDiscover => "provider.discover",
    ProviderUse => "provider.use",
    ModelList => "model.list",
    ModelGet => "model.get",
    ModelAdd => "model.add",
    ModelAlias => "model.alias",
    ModelRemove => "model.remove",
    ModelUse => "model.use",
    ModelDiscover => "model.discover",
    ModelDiscoveryStart => "model.discovery.start",
    ModelRefresh => "model.refresh",
    ModelTest => "model.test",
    ModelCapabilities => "model.capabilities",
    AgentList => "agent.list",
    AgentConfigGet => "agent.config.get",
    AgentConfigSet => "agent.config.set",
    SoulList => "soul.list",
    SoulGet => "soul.get",
    SoulCreate => "soul.create",
    SoulUpdate => "soul.update",
    SoulRemove => "soul.remove",
    SoulActivate => "soul.activate",
    SoulGetEffective => "soul.get_effective",
    SessionSoulSet => "session.soul.set",
    SessionSoulClear => "session.soul.clear",
    McpList => "mcp.list",
    McpGet => "mcp.get",
    McpCreate => "mcp.create",
    McpRemove => "mcp.remove",
    McpEnable => "mcp.enable",
    McpDisable => "mcp.disable",
    McpTest => "mcp.test",
    PluginList => "plugin.list",
    PluginGet => "plugin.get",
    PluginEnable => "plugin.enable",
    PluginDisable => "plugin.disable",
    PluginDiagnostics => "plugin.diagnostics",
    ToolList => "tool.list",
    PolicyGet => "policy.get",
    TaskTree => "task.tree",
    TaskGet => "task.get",
    VerificationLatest => "verification.latest",
    VerificationPlan => "verification.plan",
    CheckpointList => "checkpoint.list",
    CheckpointShow => "checkpoint.show",
    CheckpointRestore => "checkpoint.restore",
    PtyStart => "pty.start",
    PtyWrite => "pty.write",
    PtyResize => "pty.resize",
    PtyRead => "pty.read",
    PtyList => "pty.list",
    PtyTerminate => "pty.terminate",
    ProfileBundleList => "profile_bundle.list",
    ProfileBundleGet => "profile_bundle.get",
    ProfileBundleCreate => "profile_bundle.create",
    ProfileBundleRemove => "profile_bundle.remove",
    ProfileBundleApply => "profile_bundle.apply",
    SessionQueueAdd => "session.queue.add",
    SessionQueueList => "session.queue.list",
    SessionQueueClear => "session.queue.clear",
    SessionBranch => "session.branch",
    WorkspaceFileSearch => "workspace.file.search",
    ArtifactList => "artifact.list",
    ArtifactRead => "artifact.read",
    ArtifactExport => "artifact.export",
    ContextGet => "context.get",
    MemoryList => "memory.list",
    MemorySearch => "memory.search",
    MemoryGet => "memory.get",
    MemoryRemember => "memory.remember",
    MemoryUpdate => "memory.update",
    MemoryForget => "memory.forget",
    UsageGet => "usage.get",
    SessionClose => "session.close",
    ChannelPending => "channel.pending",
    ChannelResolve => "channel.resolve",
    ArtifactReceiveImage => "artifact.receive_image",
    ArtifactDeleteMedia => "artifact.delete_media",
    SessionImageSupport => "session.image_support",
    ArtifactMediaList => "artifact.media_list",
    AttachmentPrepare => "attachment.prepare",
    AttachmentPreview => "attachment.preview",
    AttachmentPrepareStart => "attachment.prepare.start",
    AttachmentPrepareGet => "attachment.prepare.get",
    AttachmentPrepareCancel => "attachment.prepare.cancel",
    ModelVisionSet => "model.vision.set",
    BrowserViewGet => "browser.view.get",
    WorkspaceProcessList => "workspace.process.list",
    WorkspaceProcessRead => "workspace.process.read",
    WorkspaceProcessStop => "workspace.process.stop",
}

pub const ENGINE_EVENTS: &[&str] = &[
    "turn.started",
    "turn.completed",
    "turn.failed",
    "turn.cancelled",
    "turn.stopped",
    "model.started",
    "model.content.delta",
    "model.content.completed",
    "model.completed",
    "model.failed",
    "tool.requested",
    "tool.started",
    "tool.output.delta",
    "tool.completed",
    "tool.failed",
    "tool.cancelled",
    "approval.requested",
    "approval.resolved",
    "approval.expired",
    "question.requested",
    "question.resolved",
    "question.expired",
    "session.moved",
    "governor.progress",
    "governor.nudge",
    "governor.compact",
    "governor.consolidate",
    "governor.stop",
    "usage.updated",
    "agent.started",
    "agent.completed",
    "agent.failed",
    "verification.started",
    "verification.completed",
    "verification.failed",
    "model.discovery.completed",
    "model.discovery.failed",
    "turn.changes.completed",
    "turn.changes.undo.started",
    "turn.changes.undo.completed",
    "turn.changes.undo.conflict",
    "workspace.changed",
    "channel.requested",
    "agent.activity",
];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Attachment {
    pub id: String,
    pub path: String,
    pub name: String,
    #[serde(default)]
    pub mime_type: Option<String>,
    #[serde(default)]
    pub size: Option<i64>,
    pub source: String,
    #[serde(default)]
    pub data_url: Option<String>,
    #[serde(default)]
    pub uri: Option<String>,
    #[serde(default)]
    pub sha256: Option<String>,
    #[serde(default)]
    pub kind: Option<String>,
    #[serde(default)]
    pub derived_uri: Option<String>,
    #[serde(default)]
    pub status: Option<String>,
    #[serde(default)]
    pub ocr: Option<bool>,
    #[serde(default)]
    pub truncated: Option<bool>,
    #[serde(default)]
    pub error: Option<String>,
    #[serde(default)]
    pub page_range: Option<String>,
    #[serde(default)]
    pub visual_pages: Option<Vec<i64>>,
    #[serde(default)]
    pub images: Option<Vec<serde_json::Value>>,
    #[serde(default)]
    pub warning: Option<String>,
    #[serde(default)]
    pub content_type: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSummary {
    pub id: String,
    pub kind: String,
    #[serde(default)]
    pub title: Option<String>,
    pub mode: String,
    pub state: String,
    pub updated_at: String,
    #[serde(default)]
    pub project_id: Option<String>,
    #[serde(default)]
    pub project_root: Option<String>,
    #[serde(default)]
    pub current_cwd: Option<String>,
    #[serde(default)]
    pub git_branch: Option<String>,
    pub last_active_at: String,
    pub provider_id: String,
    pub model_id: String,
    pub permission_profile: String,
    pub effective_permission_profile: String,
    #[serde(default)]
    pub read_permission_profile: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectSummary {
    pub id: String,
    pub root: String,
    pub canonical_root: String,
    pub name: String,
    pub description: String,
    pub pinned: bool,
    pub archived: bool,
    #[serde(default)]
    pub git_fingerprint: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub last_opened_at: String,
    #[serde(default)]
    pub active_session_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageSnapshot {
    pub model_calls: i64,
    pub tool_calls: i64,
    pub network_calls: i64,
    pub subagent_calls: i64,
    pub max_recursion_depth: i64,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub wall_time_s: f64,
    #[serde(default)]
    pub estimated_cost: Option<f64>,
    pub exhausted: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GovernorSnapshot {
    pub execution: String,
    pub recovery_attempts: i64,
    pub max_recovery_attempts: i64,
    pub compactions: i64,
    pub last_compacted_history_size: i64,
    #[serde(default)]
    pub context_pressure: Option<f64>,
    #[serde(default)]
    pub progress: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProtocolError {
    pub code: String,
    pub message: String,
    pub retryable: bool,
    pub details: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionOption {
    pub label: String,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub recommended: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserQuestion {
    pub id: String,
    pub title: String,
    #[serde(default)]
    pub options: Option<Vec<QuestionOption>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionRequest {
    pub request_id: String,
    pub session_id: String,
    pub turn_id: String,
    pub status: String,
    pub questions: Vec<UserQuestion>,
    #[serde(default)]
    pub answers: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilePreview {
    pub path: String,
    pub name: String,
    pub content: String,
    pub language: String,
    pub size: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebPreview {
    pub preview_id: String,
    pub session_id: String,
    pub url: String,
    pub kind: String,
    pub ready: bool,
    pub revision: i64,
    #[serde(default)]
    pub command: Option<String>,
    #[serde(default)]
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolAvailability {
    #[serde(default)]
    pub available: Option<bool>,
    pub reason: String,
    pub requires: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolSummary {
    pub name: String,
    pub description: String,
    pub risk: String,
    pub side_effects: String,
    pub namespace: String,
    #[serde(default)]
    pub capabilities: Option<Vec<String>>,
    #[serde(default)]
    pub permissions: Option<Vec<String>>,
    pub always_loaded: bool,
    #[serde(default)]
    pub availability: Option<ToolAvailability>,
    #[serde(default)]
    pub input_schema: Option<serde_json::Value>,
    #[serde(default)]
    pub output_schema: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrowserPage {
    pub target_id: String,
    pub title: String,
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrowserView {
    pub state: String,
    pub session_id: String,
    #[serde(default)]
    pub instance: Option<String>,
    #[serde(default)]
    pub image: Option<String>,
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub target_id: Option<String>,
    #[serde(default)]
    pub error: Option<String>,
    #[serde(default)]
    pub pages: Option<Vec<BrowserPage>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManagedProcess {
    pub id: String,
    pub kind: String,
    pub command: String,
    pub cwd: String,
    #[serde(default)]
    pub url: Option<String>,
    pub running: bool,
    pub can_stop: bool,
    #[serde(default)]
    pub pid: Option<i64>,
    #[serde(default)]
    pub started_at: Option<f64>,
    #[serde(default)]
    pub exit_code: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessOutput {
    pub process: ManagedProcess,
    pub stdout: String,
    pub stderr: String,
    pub truncated: bool,
}
