// @generated by scripts/generate-protocol.mjs — DO NOT EDIT.
// Source: Rinari Engine Protocol v1 (sha256:04ad482e7178fe225ed1446e2f32a8b409b8e0522d33de1300e7c330271955eb)

use serde::{Deserialize, Serialize};

macro_rules! define_methods {
    ($( $variant:ident => $name:literal ),* $(,)?) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum Method { $( $variant ),* }
        impl Method {
            pub fn as_str(self) -> &'static str {
                match self { $( Method::$variant => $name ),* }
            }
            pub const ALL: &'static [Method] = &[ $( Method::$variant ),* ];
        }
    };
}

define_methods! {
    EngineInfo => "engine.info",
    RuntimeSnapshotGet => "runtime.snapshot.get",
    SessionList => "session.list",
    SessionGet => "session.get",
    SessionCreate => "session.create",
    SessionOpen => "session.open",
    SessionRename => "session.rename",
    SessionArchive => "session.archive",
    SessionRestore => "session.restore",
    SessionDelete => "session.delete",
    SessionFork => "session.fork",
    SessionHistory => "session.history",
    SessionModeSet => "session.mode.set",
    SessionModelSet => "session.model.set",
    SessionPermissionGet => "session.permission.get",
    SessionPermissionSet => "session.permission.set",
    SessionTurnStart => "session.turn.start",
    SessionTurnCancel => "session.turn.cancel",
    SessionEvents => "session.events",
    SessionTimeline => "session.timeline",
    ApprovalResolve => "approval.resolve",
    TurnChangesGet => "turn.changes.get",
    TurnChangesReview => "turn.changes.review",
    TurnChangesUndoPreview => "turn.changes.undo.preview",
    TurnChangesUndo => "turn.changes.undo",
    ProjectList => "project.list",
    ProjectGet => "project.get",
    ProjectAdd => "project.add",
    ProjectUpdate => "project.update",
    ProjectRemove => "project.remove",
    ProjectListRecent => "project.list_recent",
    ProjectOpen => "project.open",
    ProjectStatus => "project.status",
    ProjectIntelligence => "project.intelligence",
    ProjectTrust => "project.trust",
    ProjectChanges => "project.changes",
    ProjectDiff => "project.diff",
    ProviderList => "provider.list",
    ProviderGet => "provider.get",
    ProviderCreate => "provider.create",
    ProviderUpdate => "provider.update",
    ProviderRemove => "provider.remove",
    ProviderTest => "provider.test",
    ProviderDiscover => "provider.discover",
    ProviderUse => "provider.use",
    ModelList => "model.list",
    ModelGet => "model.get",
    ModelAdd => "model.add",
    ModelAlias => "model.alias",
    ModelRemove => "model.remove",
    ModelUse => "model.use",
    ModelDiscover => "model.discover",
    ModelDiscoveryStart => "model.discovery.start",
    ModelRefresh => "model.refresh",
    ModelTest => "model.test",
    ModelCapabilities => "model.capabilities",
    AgentList => "agent.list",
    AgentConfigGet => "agent.config.get",
    AgentConfigSet => "agent.config.set",
    SoulList => "soul.list",
    SoulGet => "soul.get",
    SoulCreate => "soul.create",
    SoulUpdate => "soul.update",
    SoulRemove => "soul.remove",
    SoulActivate => "soul.activate",
    SoulGetEffective => "soul.get_effective",
    SessionSoulSet => "session.soul.set",
    SessionSoulClear => "session.soul.clear",
    McpList => "mcp.list",
    McpGet => "mcp.get",
    McpCreate => "mcp.create",
    McpRemove => "mcp.remove",
    McpEnable => "mcp.enable",
    McpDisable => "mcp.disable",
    McpTest => "mcp.test",
    PluginList => "plugin.list",
    PluginGet => "plugin.get",
    PluginEnable => "plugin.enable",
    PluginDisable => "plugin.disable",
    PluginDiagnostics => "plugin.diagnostics",
    ToolList => "tool.list",
    PolicyGet => "policy.get",
    TaskTree => "task.tree",
    TaskGet => "task.get",
    VerificationLatest => "verification.latest",
    VerificationPlan => "verification.plan",
    CheckpointList => "checkpoint.list",
    CheckpointShow => "checkpoint.show",
    CheckpointRestore => "checkpoint.restore",
    PtyStart => "pty.start",
    PtyWrite => "pty.write",
    PtyResize => "pty.resize",
    PtyRead => "pty.read",
    PtyList => "pty.list",
    PtyTerminate => "pty.terminate",
    ProfileBundleList => "profile_bundle.list",
    ProfileBundleGet => "profile_bundle.get",
    ProfileBundleCreate => "profile_bundle.create",
    ProfileBundleRemove => "profile_bundle.remove",
    ProfileBundleApply => "profile_bundle.apply",
    SessionQueueAdd => "session.queue.add",
    SessionQueueList => "session.queue.list",
    SessionQueueClear => "session.queue.clear",
    SessionBranch => "session.branch",
    WorkspaceFileSearch => "workspace.file.search",
    ArtifactList => "artifact.list",
    ArtifactRead => "artifact.read",
    ArtifactExport => "artifact.export",
    ContextGet => "context.get",
    UsageGet => "usage.get",
    SessionClose => "session.close",
}

pub const ENGINE_EVENTS: &[&str] = &[
    "turn.started",
    "turn.completed",
    "turn.failed",
    "turn.cancelled",
    "turn.stopped",
    "model.started",
    "model.content.delta",
    "model.content.completed",
    "model.completed",
    "model.failed",
    "tool.requested",
    "tool.started",
    "tool.output.delta",
    "tool.completed",
    "tool.failed",
    "tool.cancelled",
    "approval.requested",
    "approval.resolved",
    "approval.expired",
    "governor.progress",
    "governor.nudge",
    "governor.compact",
    "governor.consolidate",
    "governor.stop",
    "usage.updated",
    "agent.started",
    "agent.completed",
    "agent.failed",
    "verification.started",
    "verification.completed",
    "verification.failed",
    "model.discovery.completed",
    "model.discovery.failed",
    "turn.changes.completed",
    "turn.changes.undo.started",
    "turn.changes.undo.completed",
    "turn.changes.undo.conflict",
    "workspace.changed",
];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Attachment {
    pub id: String,
    pub path: String,
    pub name: String,
    #[serde(default)]
    pub mime_type: Option<String>,
    #[serde(default)]
    pub size: Option<i64>,
    pub source: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSummary {
    pub id: String,
    pub kind: String,
    #[serde(default)]
    pub title: Option<String>,
    pub mode: String,
    pub state: String,
    pub updated_at: String,
    #[serde(default)]
    pub project_id: Option<String>,
    #[serde(default)]
    pub project_root: Option<String>,
    #[serde(default)]
    pub current_cwd: Option<String>,
    #[serde(default)]
    pub git_branch: Option<String>,
    pub last_active_at: String,
    pub provider_id: String,
    pub model_id: String,
    pub permission_profile: String,
    pub effective_permission_profile: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectSummary {
    pub id: String,
    pub root: String,
    pub canonical_root: String,
    pub name: String,
    pub description: String,
    pub pinned: bool,
    pub archived: bool,
    #[serde(default)]
    pub git_fingerprint: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub last_opened_at: String,
    #[serde(default)]
    pub active_session_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageSnapshot {
    pub model_calls: i64,
    pub tool_calls: i64,
    pub network_calls: i64,
    pub subagent_calls: i64,
    pub max_recursion_depth: i64,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub wall_time_s: f64,
    #[serde(default)]
    pub estimated_cost: Option<f64>,
    pub exhausted: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GovernorSnapshot {
    pub execution: String,
    pub recovery_attempts: i64,
    pub max_recovery_attempts: i64,
    pub compactions: i64,
    pub last_compacted_history_size: i64,
    #[serde(default)]
    pub context_pressure: Option<f64>,
    #[serde(default)]
    pub progress: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProtocolError {
    pub code: String,
    pub message: String,
    pub retryable: bool,
    pub details: serde_json::Value,
}
