// @generated by scripts/generate-protocol.mjs — DO NOT EDIT.
// Source: Rinari Engine Protocol v1 (sha256:d97c3267ecfb98aabf6a346b31a76ae4423bcd97daef76dc226ab7e53e1c69ef)

export const ENGINE_METHODS = [
  "engine.info",
  "runtime.snapshot.get",
  "session.move",
  "workspace.file.read",
  "workspace.preview.start",
  "workspace.preview.status",
  "workspace.preview.stop",
  "question.list",
  "question.resolve",
  "session.list",
  "session.get",
  "session.create",
  "session.open",
  "session.rename",
  "session.archive",
  "session.restore",
  "session.delete",
  "session.fork",
  "session.history",
  "session.mode.set",
  "session.model.set",
  "session.permission.get",
  "session.permission.set",
  "session.turn.start",
  "target.list",
  "target.add",
  "operation.start",
  "operation.get",
  "operation.cancel",
  "session.turn.cancel",
  "session.events",
  "session.timeline",
  "approval.resolve",
  "turn.changes.get",
  "turn.changes.review",
  "turn.changes.undo.preview",
  "turn.changes.undo",
  "project.list",
  "project.get",
  "project.add",
  "project.update",
  "project.remove",
  "project.list_recent",
  "project.open",
  "project.status",
  "project.intelligence",
  "project.trust",
  "project.changes",
  "project.diff",
  "provider.list",
  "provider.get",
  "provider.create",
  "provider.update",
  "provider.remove",
  "provider.test",
  "provider.discover",
  "provider.use",
  "model.list",
  "model.get",
  "model.add",
  "model.alias",
  "model.remove",
  "model.use",
  "model.discover",
  "model.discovery.start",
  "model.refresh",
  "model.test",
  "model.capabilities",
  "agent.list",
  "agent.config.get",
  "agent.config.set",
  "soul.list",
  "soul.get",
  "soul.create",
  "soul.update",
  "soul.remove",
  "soul.activate",
  "soul.get_effective",
  "session.soul.set",
  "session.soul.clear",
  "mcp.list",
  "mcp.get",
  "mcp.create",
  "mcp.remove",
  "mcp.enable",
  "mcp.disable",
  "mcp.test",
  "plugin.list",
  "plugin.get",
  "plugin.enable",
  "plugin.disable",
  "plugin.diagnostics",
  "tool.list",
  "policy.get",
  "task.tree",
  "task.get",
  "verification.latest",
  "verification.plan",
  "checkpoint.list",
  "checkpoint.show",
  "checkpoint.restore",
  "pty.start",
  "pty.write",
  "pty.resize",
  "pty.read",
  "pty.list",
  "pty.terminate",
  "profile_bundle.list",
  "profile_bundle.get",
  "profile_bundle.create",
  "profile_bundle.remove",
  "profile_bundle.apply",
  "session.queue.add",
  "session.queue.list",
  "session.queue.clear",
  "session.branch",
  "workspace.file.search",
  "artifact.list",
  "artifact.read",
  "artifact.export",
  "context.get",
  "memory.list",
  "memory.search",
  "memory.get",
  "memory.remember",
  "memory.update",
  "memory.forget",
  "usage.get",
  "session.close",
  "channel.pending",
  "channel.resolve",
  "artifact.receive_image",
  "artifact.delete_media",
  "session.image_support",
  "artifact.media_list",
  "attachment.prepare",
  "attachment.preview",
  "attachment.prepare.start",
  "attachment.prepare.get",
  "attachment.prepare.cancel",
  "model.vision.set"
] as const
export type EngineMethod = (typeof ENGINE_METHODS)[number]

export const ENGINE_EVENTS = [
  "turn.started",
  "turn.completed",
  "turn.failed",
  "turn.cancelled",
  "turn.stopped",
  "model.started",
  "model.content.delta",
  "model.content.completed",
  "model.completed",
  "model.failed",
  "tool.requested",
  "tool.started",
  "tool.output.delta",
  "tool.completed",
  "tool.failed",
  "tool.cancelled",
  "approval.requested",
  "approval.resolved",
  "approval.expired",
  "question.requested",
  "question.resolved",
  "question.expired",
  "session.moved",
  "governor.progress",
  "governor.nudge",
  "governor.compact",
  "governor.consolidate",
  "governor.stop",
  "usage.updated",
  "agent.started",
  "agent.completed",
  "agent.failed",
  "verification.started",
  "verification.completed",
  "verification.failed",
  "model.discovery.completed",
  "model.discovery.failed",
  "turn.changes.completed",
  "turn.changes.undo.started",
  "turn.changes.undo.completed",
  "turn.changes.undo.conflict",
  "workspace.changed",
  "channel.requested"
] as const
export type EngineEventName = (typeof ENGINE_EVENTS)[number]

export interface Attachment {
  id: string
  path: string
  name: string
  mime_type?: string | null
  size?: number | null
  source: "native" | "workspace"
  data_url?: string | null
  uri?: string | null
  sha256?: string | null
  kind?: string | null
  derived_uri?: string | null
  status?: string | null
  ocr?: boolean | null
  truncated?: boolean | null
  error?: string | null
  page_range?: string | null
  visual_pages?: Array<number> | null
  images?: Array<Record<string, unknown>> | null
  warning?: string | null
  content_type?: string | null
}

export interface SessionSummary {
  id: string
  kind: "CHAT" | "PROJECT"
  title: string | null
  mode: "plan" | "build" | "review"
  state: "active" | "closed" | "archived"
  updated_at: string
  project_id: string | null
  project_root: string | null
  current_cwd: string | null
  git_branch: string | null
  last_active_at: string
  provider_id: string
  model_id: string
  permission_profile: "read-only" | "workspace" | "full-access"
  effective_permission_profile: "read-only" | "workspace" | "full-access"
  read_permission_profile?: "read-only" | "workspace" | "full-access"
}

export interface ProjectSummary {
  id: string
  root: string
  canonical_root: string
  name: string
  description: string
  pinned: boolean
  archived: boolean
  git_fingerprint: string | null
  created_at: string
  updated_at: string
  last_opened_at: string
  active_session_id?: string | null
}

export interface UsageSnapshot {
  model_calls: number
  tool_calls: number
  network_calls: number
  subagent_calls: number
  max_recursion_depth: number
  input_tokens: number
  output_tokens: number
  wall_time_s: number
  estimated_cost?: number | null
  exhausted: Array<string>
}

export interface GovernorSnapshot {
  execution: "automatic"
  recovery_attempts: number
  max_recovery_attempts: number
  compactions: number
  last_compacted_history_size: number
  context_pressure: number | null
  progress: Record<string, unknown> | null
}

export interface ProtocolError {
  code: string
  message: string
  retryable: boolean
  details: Record<string, unknown>
}

export interface QuestionOption {
  label: string
  description?: string
  recommended?: boolean
}

export interface UserQuestion {
  id: string
  title: string
  options?: Array<QuestionOption>
}

export interface QuestionRequest {
  request_id: string
  session_id: string
  turn_id: string
  status: "pending" | "answered" | "skipped" | "expired"
  questions: Array<UserQuestion>
  answers?: Record<string, string>
}

export interface FilePreview {
  path: string
  name: string
  content: string
  language: string
  size: number
}

export interface WebPreview {
  preview_id: string
  session_id: string
  url: string
  kind: "static" | "development"
  ready: boolean
  revision: number
  command?: string | null
  error?: string | null
}

export interface ToolAvailability {
  available: boolean | null
  reason: string
  requires: Array<string>
}

export interface ToolSummary {
  name: string
  description: string
  risk: string
  side_effects: string
  namespace: string
  capabilities: Array<string> | null
  permissions: Array<string> | null
  always_loaded: boolean
  availability?: ToolAvailability
  input_schema?: Record<string, unknown>
  output_schema?: Record<string, unknown> | null
}
